### ISSUE TITLE
Backend service is unhealty

### ISSUE THREAD

**Issue by elmehdi-eljair** [brownboycodes/Paypal-Concept-Flutter#18]
Hi dears, 

First, thank you for this sharing, 

But the backends needed for athentification doesn"t work. Could you help to connect to the right backends ?

Thanks,

**Comment by brownboycodes** [comment]
Hi, thank you for showing interest in my project; 
a temporary failure to did occur about a few days ago because of the hosting service being used, but that issue had been resolved soon after it occurred and the backend has been working fine since then. Therefore, I am closing this issue.
